# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cao Jilin
email: caojilin138@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The sharp edge of a razor is difficult to pass over;
  thus the wise say the path to Salvation is hard.

# baseurl: "/about" # the subpath of your site, e.g. /blog
# url: "//opieters.github.io" # the base hostname & protocol for your site
twitter_username: bohemian
github_username:  caojilin

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "photography"
    values:
      permalink: /:path/:basename:output_ext

exclude: [LICENSE-CODE.md, LICENSE-IMAGES, README.md, bower.json]
